ETL:
  target: clickhouse
  outputs:
    clickhouse:
      type: clickhouse
      host: lbanrxx268.ap-southeast-1.aws.clickhouse.cloud
      user: default
      password: ~WfW3boz~nJtl
      port: 8443
      secure: True